// <auto-generated />
namespace Hangar.Restaurant.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class price_float_to_decimal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(price_float_to_decimal));
        
        string IMigrationMetadata.Id
        {
            get { return "202007200733586_price_float_to_decimal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
