// <auto-generated />
namespace Hangar.Restaurant.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class foreign_key_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foreign_key_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202007300743368_foreign_key_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
